/**
 * National Dex #1–493 species data for gameplay tuning (height, motion, type logic).
 * Regenerate: `node scripts/build-pokemon-config.mjs` (needs network).
 *
 * @typedef {'bug'|'dark'|'dragon'|'electric'|'fairy'|'fighting'|'fire'|'flying'|'ghost'|'grass'|'ground'|'ice'|'normal'|'poison'|'psychic'|'rock'|'steel'|'water'} PokemonTypeSlug
 *
 * @typedef {Object} PokemonBehaviorTuning
 * @property {number} [walkSpeedMul] — multiply walk tick scale (1 = default)
 * @property {number} [scatterWeight] — encounter / prop scatter preference weight
 * @property {number} [turnBias] — −1..1 AI turn randomness bias (reserved)
 *
 * @typedef {Object} PokemonSpeciesConfig
 * @property {string} name — matches encounter strings in national-dex-registry.js where possible
 * @property {PokemonTypeSlug[]} types — slot order primary → secondary; Gen 1 chart overrides baked in (see script)
 * @property {number} heightTiles — visual / collider height in tile units
 * @property {number} baseSpeed — main-series base Speed (for motion / turn order tuning)
 * @property {PokemonBehaviorTuning} [behavior] — optional per-species behavior overrides
 */

/** @type {Record<number, PokemonSpeciesConfig>} */
export const POKEMON_CONFIG = {
  1: { name: 'Bulbasaur', types: ['grass', 'poison'], heightTiles: 2.1, baseSpeed: 45 },
  2: { name: 'Ivysaur', types: ['grass', 'poison'], heightTiles: 2.2, baseSpeed: 60 },
  3: { name: 'Venusaur', types: ['grass', 'poison'], heightTiles: 2.5, baseSpeed: 80 },
  4: { name: 'Charmander', types: ['fire'], heightTiles: 2.5, baseSpeed: 65 },
  5: { name: 'Charmeleon', types: ['fire'], heightTiles: 3.5, baseSpeed: 80 },
  6: { name: 'Charizard', types: ['fire', 'flying'], heightTiles: 3.5, baseSpeed: 100 },
  7: { name: 'Squirtle', types: ['water'], heightTiles: 1.5, baseSpeed: 43 },
  8: { name: 'Wartortle', types: ['water'], heightTiles: 2.5, baseSpeed: 58 },
  9: { name: 'Blastoise', types: ['water'], heightTiles: 3.1, baseSpeed: 78 },
  10: { name: 'Caterpie', types: ['bug'], heightTiles: 2, baseSpeed: 45 },
  11: { name: 'Metapod', types: ['bug'], heightTiles: 2.1, baseSpeed: 30 },
  12: { name: 'Butterfree', types: ['bug', 'flying'], heightTiles: 3.3, baseSpeed: 70 },
  13: { name: 'Weedle', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 50 },
  14: { name: 'Kakuna', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 35 },
  15: { name: 'Beedrill', types: ['bug', 'poison'], heightTiles: 3, baseSpeed: 75 },
  16: { name: 'Pidgey', types: ['normal', 'flying'], heightTiles: 2, baseSpeed: 56 },
  17: { name: 'Pidgeotto', types: ['normal', 'flying'], heightTiles: 3.2, baseSpeed: 71 },
  18: { name: 'Pidgeot', types: ['normal', 'flying'], heightTiles: 3.7, baseSpeed: 101 },
  19: { name: 'Rattata', types: ['normal'], heightTiles: 1.6, baseSpeed: 72 },
  20: { name: 'Raticate', types: ['normal'], heightTiles: 3.5, baseSpeed: 97 },
  21: { name: 'Spearow', types: ['normal', 'flying'], heightTiles: 2.5, baseSpeed: 70 },
  22: { name: 'Fearow', types: ['normal', 'flying'], heightTiles: 5.2, baseSpeed: 100 },
  23: { name: 'Ekans', types: ['poison'], heightTiles: 2.5, baseSpeed: 55 },
  24: { name: 'Arbok', types: ['poison'], heightTiles: 3.5, baseSpeed: 80 },
  25: { name: 'Pikachu', types: ['electric'], heightTiles: 2.9, baseSpeed: 90 },
  26: { name: 'Raichu', types: ['electric'], heightTiles: 3.5, baseSpeed: 110 },
  27: { name: 'Sandshrew', types: ['ground'], heightTiles: 2.5, baseSpeed: 40 },
  28: { name: 'Sandslash', types: ['ground'], heightTiles: 3, baseSpeed: 65 },
  29: { name: 'Nidoran♀', types: ['poison'], heightTiles: 2.5, baseSpeed: 41 },
  30: { name: 'Nidorina', types: ['poison'], heightTiles: 3.5, baseSpeed: 56 },
  31: { name: 'Nidoqueen', types: ['poison', 'ground'], heightTiles: 3.5, baseSpeed: 76 },
  32: { name: 'Nidoran♂', types: ['poison'], heightTiles: 2.5, baseSpeed: 50 },
  33: { name: 'Nidorino', types: ['poison'], heightTiles: 2.9, baseSpeed: 65 },
  34: { name: 'Nidoking', types: ['poison', 'ground'], heightTiles: 3.6, baseSpeed: 85 },
  35: { name: 'Clefairy', types: ['normal'], heightTiles: 2.5, baseSpeed: 35 },
  36: { name: 'Clefable', types: ['normal'], heightTiles: 3.5, baseSpeed: 60 },
  37: { name: 'Vulpix', types: ['fire'], heightTiles: 1.7, baseSpeed: 65 },
  38: { name: 'Ninetales', types: ['fire'], heightTiles: 3.1, baseSpeed: 100 },
  39: { name: 'Jigglypuff', types: ['normal'], heightTiles: 2.1, baseSpeed: 20 },
  40: { name: 'Wigglytuff', types: ['normal'], heightTiles: 3.5, baseSpeed: 45 },
  41: { name: 'Zubat', types: ['poison', 'flying'], heightTiles: 2.7, baseSpeed: 55 },
  42: { name: 'Golbat', types: ['poison', 'flying'], heightTiles: 4.1, baseSpeed: 90 },
  43: { name: 'Oddish', types: ['grass', 'poison'], heightTiles: 2, baseSpeed: 30 },
  44: { name: 'Gloom', types: ['grass', 'poison'], heightTiles: 2.1, baseSpeed: 40 },
  45: { name: 'Vileplume', types: ['grass', 'poison'], heightTiles: 3.5, baseSpeed: 50 },
  46: { name: 'Paras', types: ['bug', 'grass'], heightTiles: 1.5, baseSpeed: 25 },
  47: { name: 'Parasect', types: ['bug', 'grass'], heightTiles: 3.5, baseSpeed: 30 },
  48: { name: 'Venonat', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 45 },
  49: { name: 'Venomoth', types: ['bug', 'poison'], heightTiles: 4.1, baseSpeed: 90 },
  50: { name: 'Diglett', types: ['ground'], heightTiles: 1.2, baseSpeed: 95 },
  51: { name: 'Dugtrio', types: ['ground'], heightTiles: 1.8, baseSpeed: 120 },
  52: { name: 'Meowth', types: ['normal'], heightTiles: 2, baseSpeed: 90 },
  53: { name: 'Persian', types: ['normal'], heightTiles: 3.8, baseSpeed: 115 },
  54: { name: 'Psyduck', types: ['water'], heightTiles: 2.5, baseSpeed: 55 },
  55: { name: 'Golduck', types: ['water'], heightTiles: 2.7, baseSpeed: 85 },
  56: { name: 'Mankey', types: ['fighting'], heightTiles: 3.2, baseSpeed: 70 },
  57: { name: 'Primeape', types: ['fighting'], heightTiles: 4.7, baseSpeed: 95 },
  58: { name: 'Growlithe', types: ['fire'], heightTiles: 2.5, baseSpeed: 60 },
  59: { name: 'Arcanine', types: ['fire'], heightTiles: 3.5, baseSpeed: 95 },
  60: { name: 'Poliwag', types: ['water'], heightTiles: 2.5, baseSpeed: 90 },
  61: { name: 'Poliwhirl', types: ['water'], heightTiles: 3.5, baseSpeed: 90 },
  62: { name: 'Poliwrath', types: ['water', 'fighting'], heightTiles: 4.1, baseSpeed: 70 },
  63: { name: 'Abra', types: ['psychic'], heightTiles: 2.5, baseSpeed: 90 },
  64: { name: 'Kadabra', types: ['psychic'], heightTiles: 3.5, baseSpeed: 105 },
  65: { name: 'Alakazam', types: ['psychic'], heightTiles: 4, baseSpeed: 120 },
  66: { name: 'Machop', types: ['fighting'], heightTiles: 2.2, baseSpeed: 35 },
  67: { name: 'Machoke', types: ['fighting'], heightTiles: 3.5, baseSpeed: 45 },
  68: { name: 'Machamp', types: ['fighting'], heightTiles: 3.5, baseSpeed: 55 },
  69: { name: 'Bellsprout', types: ['grass', 'poison'], heightTiles: 2.15, baseSpeed: 40 },
  70: { name: 'Weepinbell', types: ['grass', 'poison'], heightTiles: 3.1, baseSpeed: 55 },
  71: { name: 'Victreebel', types: ['grass', 'poison'], heightTiles: 5.7, baseSpeed: 70 },
  72: { name: 'Tentacool', types: ['water', 'poison'], heightTiles: 2.5, baseSpeed: 70 },
  73: { name: 'Tentacruel', types: ['water', 'poison'], heightTiles: 5.7, baseSpeed: 100 },
  74: { name: 'Geodude', types: ['rock', 'ground'], heightTiles: 1.3, baseSpeed: 20 },
  75: { name: 'Graveler', types: ['rock', 'ground'], heightTiles: 3.1, baseSpeed: 35 },
  76: { name: 'Golem', types: ['rock', 'ground'], heightTiles: 3.2, baseSpeed: 45 },
  77: { name: 'Ponyta', types: ['fire'], heightTiles: 2.6, baseSpeed: 90 },
  78: { name: 'Rapidash', types: ['fire'], heightTiles: 3.9, baseSpeed: 105 },
  79: { name: 'Slowpoke', types: ['water', 'psychic'], heightTiles: 2.5, baseSpeed: 15 },
  80: { name: 'Slowbro', types: ['water', 'psychic'], heightTiles: 3.5, baseSpeed: 30 },
  81: { name: 'Magnemite', types: ['electric'], heightTiles: 2.4, baseSpeed: 45 },
  82: { name: 'Magneton', types: ['electric'], heightTiles: 3.1, baseSpeed: 70 },
  83: { name: 'Farfetch\'d', types: ['normal', 'flying'], heightTiles: 2.1, baseSpeed: 60 },
  84: { name: 'Doduo', types: ['normal', 'flying'], heightTiles: 2.5, baseSpeed: 75 },
  85: { name: 'Dodrio', types: ['normal', 'flying'], heightTiles: 3.6, baseSpeed: 110 },
  86: { name: 'Seel', types: ['water'], heightTiles: 2, baseSpeed: 45 },
  87: { name: 'Dewgong', types: ['water', 'ice'], heightTiles: 3.1, baseSpeed: 70 },
  88: { name: 'Grimer', types: ['poison'], heightTiles: 2.5, baseSpeed: 25 },
  89: { name: 'Muk', types: ['poison'], heightTiles: 3.4, baseSpeed: 50 },
  90: { name: 'Shellder', types: ['water'], heightTiles: 2.2, baseSpeed: 40 },
  91: { name: 'Cloyster', types: ['water', 'ice'], heightTiles: 4.3, baseSpeed: 70 },
  92: { name: 'Gastly', types: ['ghost', 'poison'], heightTiles: 2.5, baseSpeed: 80 },
  93: { name: 'Haunter', types: ['ghost', 'poison'], heightTiles: 3.5, baseSpeed: 95 },
  94: { name: 'Gengar', types: ['ghost', 'poison'], heightTiles: 3.1, baseSpeed: 110 },
  95: { name: 'Onix', types: ['rock', 'ground'], heightTiles: 9, baseSpeed: 70 },
  96: { name: 'Drowzee', types: ['psychic'], heightTiles: 2.7, baseSpeed: 42 },
  97: { name: 'Hypno', types: ['psychic'], heightTiles: 3.8, baseSpeed: 67 },
  98: { name: 'Krabby', types: ['water'], heightTiles: 2.5, baseSpeed: 50 },
  99: { name: 'Kingler', types: ['water'], heightTiles: 4.9, baseSpeed: 75 },
  100: { name: 'Voltorb', types: ['electric'], heightTiles: 2.5, baseSpeed: 100 },
  101: { name: 'Electrode', types: ['electric'], heightTiles: 3.5, baseSpeed: 150 },
  102: { name: 'Exeggcute', types: ['grass', 'psychic'], heightTiles: 2.5, baseSpeed: 40 },
  103: { name: 'Exeggutor', types: ['grass', 'psychic'], heightTiles: 4.2, baseSpeed: 55 },
  104: { name: 'Cubone', types: ['ground'], heightTiles: 2.5, baseSpeed: 35 },
  105: { name: 'Marowak', types: ['ground'], heightTiles: 2.9, baseSpeed: 45 },
  106: { name: 'Hitmonlee', types: ['fighting'], heightTiles: 3.2, baseSpeed: 87 },
  107: { name: 'Hitmonchan', types: ['fighting'], heightTiles: 4.3, baseSpeed: 76 },
  108: { name: 'Lickitung', types: ['normal'], heightTiles: 3.5, baseSpeed: 30 },
  109: { name: 'Koffing', types: ['poison'], heightTiles: 3.2, baseSpeed: 35 },
  110: { name: 'Weezing', types: ['poison'], heightTiles: 4.2, baseSpeed: 60 },
  111: { name: 'Rhyhorn', types: ['ground', 'rock'], heightTiles: 2.5, baseSpeed: 25 },
  112: { name: 'Rhydon', types: ['ground', 'rock'], heightTiles: 3.9, baseSpeed: 40 },
  113: { name: 'Chansey', types: ['normal'], heightTiles: 3.5, baseSpeed: 50 },
  114: { name: 'Tangela', types: ['grass'], heightTiles: 2.6, baseSpeed: 60 },
  115: { name: 'Kangaskhan', types: ['normal'], heightTiles: 4.7, baseSpeed: 90 },
  116: { name: 'Horsea', types: ['water'], heightTiles: 3.2, baseSpeed: 60 },
  117: { name: 'Seadra', types: ['water'], heightTiles: 4.5, baseSpeed: 85 },
  118: { name: 'Goldeen', types: ['water'], heightTiles: 2.5, baseSpeed: 63 },
  119: { name: 'Seaking', types: ['water'], heightTiles: 3.5, baseSpeed: 68 },
  120: { name: 'Staryu', types: ['water'], heightTiles: 1.9, baseSpeed: 85 },
  121: { name: 'Starmie', types: ['water', 'psychic'], heightTiles: 2.5, baseSpeed: 115 },
  122: { name: 'Mr. Mime', types: ['psychic'], heightTiles: 3.5, baseSpeed: 90 },
  123: { name: 'Scyther', types: ['bug', 'flying'], heightTiles: 3.5, baseSpeed: 105 },
  124: { name: 'Jynx', types: ['ice', 'psychic'], heightTiles: 2.3, baseSpeed: 95 },
  125: { name: 'Electabuzz', types: ['electric'], heightTiles: 3.5, baseSpeed: 105 },
  126: { name: 'Magmar', types: ['fire'], heightTiles: 3.5, baseSpeed: 93 },
  127: { name: 'Pinsir', types: ['bug'], heightTiles: 3.1, baseSpeed: 85 },
  128: { name: 'Tauros', types: ['normal'], heightTiles: 3.4, baseSpeed: 110 },
  129: { name: 'Magikarp', types: ['water'], heightTiles: 1.5, baseSpeed: 80 },
  130: { name: 'Gyarados', types: ['water', 'flying'], heightTiles: 8, baseSpeed: 81 },
  131: { name: 'Lapras', types: ['water', 'ice'], heightTiles: 3.5, baseSpeed: 60 },
  132: { name: 'Ditto', types: ['normal'], heightTiles: 2, baseSpeed: 48 },
  133: { name: 'Eevee', types: ['normal'], heightTiles: 1.9, baseSpeed: 55 },
  134: { name: 'Vaporeon', types: ['water'], heightTiles: 3, baseSpeed: 65 },
  135: { name: 'Jolteon', types: ['electric'], heightTiles: 3, baseSpeed: 130 },
  136: { name: 'Flareon', types: ['fire'], heightTiles: 2.5, baseSpeed: 65 },
  137: { name: 'Porygon', types: ['normal'], heightTiles: 2.5, baseSpeed: 40 },
  138: { name: 'Omanyte', types: ['rock', 'water'], heightTiles: 2.1, baseSpeed: 35 },
  139: { name: 'Omastar', types: ['rock', 'water'], heightTiles: 3, baseSpeed: 55 },
  140: { name: 'Kabuto', types: ['rock', 'water'], heightTiles: 1.5, baseSpeed: 55 },
  141: { name: 'Kabutops', types: ['rock', 'water'], heightTiles: 3.5, baseSpeed: 80 },
  142: { name: 'Aerodactyl', types: ['rock', 'flying'], heightTiles: 4.5, baseSpeed: 130 },
  143: { name: 'Snorlax', types: ['normal'], heightTiles: 6.2, baseSpeed: 30 },
  144: { name: 'Articuno', types: ['ice', 'flying'], heightTiles: 7, baseSpeed: 85 },
  145: { name: 'Zapdos', types: ['electric', 'flying'], heightTiles: 7, baseSpeed: 100 },
  146: { name: 'Moltres', types: ['fire', 'flying'], heightTiles: 7, baseSpeed: 90 },
  147: { name: 'Dratini', types: ['dragon'], heightTiles: 2, baseSpeed: 50 },
  148: { name: 'Dragonair', types: ['dragon'], heightTiles: 3, baseSpeed: 70 },
  149: { name: 'Dragonite', types: ['dragon', 'flying'], heightTiles: 4.4, baseSpeed: 80 },
  150: { name: 'Mewtwo', types: ['psychic'], heightTiles: 4.1, baseSpeed: 130 },
  151: { name: 'Mew', types: ['psychic'], heightTiles: 3.5, baseSpeed: 100 },
  152: { name: 'Chikorita', types: ['grass'], heightTiles: 2.5, baseSpeed: 45 },
  153: { name: 'Bayleef', types: ['grass'], heightTiles: 3.5, baseSpeed: 60 },
  154: { name: 'Meganium', types: ['grass'], heightTiles: 3.7, baseSpeed: 80 },
  155: { name: 'Cyndaquil', types: ['fire'], heightTiles: 1.65, baseSpeed: 65 },
  156: { name: 'Quilava', types: ['fire'], heightTiles: 1.45, baseSpeed: 80 },
  157: { name: 'Typhlosion', types: ['fire'], heightTiles: 4.1, baseSpeed: 100 },
  158: { name: 'Totodile', types: ['water'], heightTiles: 2.4, baseSpeed: 43 },
  159: { name: 'Croconaw', types: ['water'], heightTiles: 3, baseSpeed: 58 },
  160: { name: 'Feraligatr', types: ['water'], heightTiles: 4.2, baseSpeed: 78 },
  161: { name: 'Sentret', types: ['normal'], heightTiles: 3.5, baseSpeed: 20 },
  162: { name: 'Furret', types: ['normal'], heightTiles: 1.8, baseSpeed: 90 },
  163: { name: 'Hoothoot', types: ['normal', 'flying'], heightTiles: 1.85, baseSpeed: 50 },
  164: { name: 'Noctowl', types: ['normal', 'flying'], heightTiles: 4.6, baseSpeed: 70 },
  165: { name: 'Ledyba', types: ['bug', 'flying'], heightTiles: 2.3, baseSpeed: 55 },
  166: { name: 'Ledian', types: ['bug', 'flying'], heightTiles: 3.2, baseSpeed: 85 },
  167: { name: 'Spinarak', types: ['bug', 'poison'], heightTiles: 1.2, baseSpeed: 30 },
  168: { name: 'Ariados', types: ['bug', 'poison'], heightTiles: 3.5, baseSpeed: 40 },
  169: { name: 'Crobat', types: ['poison', 'flying'], heightTiles: 4.8, baseSpeed: 130 },
  170: { name: 'Chinchou', types: ['water', 'electric'], heightTiles: 2.2, baseSpeed: 67 },
  171: { name: 'Lanturn', types: ['water', 'electric'], heightTiles: 3.7, baseSpeed: 67 },
  172: { name: 'Pichu', types: ['electric'], heightTiles: 1.8, baseSpeed: 60 },
  173: { name: 'Cleffa', types: ['fairy'], heightTiles: 1.1, baseSpeed: 15 },
  174: { name: 'Igglybuff', types: ['normal', 'fairy'], heightTiles: 1.1, baseSpeed: 15 },
  175: { name: 'Togepi', types: ['fairy'], heightTiles: 1.8, baseSpeed: 20 },
  176: { name: 'Togetic', types: ['fairy', 'flying'], heightTiles: 2.7, baseSpeed: 40 },
  177: { name: 'Natu', types: ['psychic', 'flying'], heightTiles: 1.5, baseSpeed: 70 },
  178: { name: 'Xatu', types: ['psychic', 'flying'], heightTiles: 2.5, baseSpeed: 95 },
  179: { name: 'Mareep', types: ['electric'], heightTiles: 2.4, baseSpeed: 35 },
  180: { name: 'Flaaffy', types: ['electric'], heightTiles: 3, baseSpeed: 45 },
  181: { name: 'Ampharos', types: ['electric'], heightTiles: 4.2, baseSpeed: 55 },
  182: { name: 'Bellossom', types: ['grass'], heightTiles: 1.5, baseSpeed: 50 },
  183: { name: 'Marill', types: ['water', 'fairy'], heightTiles: 2, baseSpeed: 40 },
  184: { name: 'Azumarill', types: ['water', 'fairy'], heightTiles: 2.9, baseSpeed: 50 },
  185: { name: 'Sudowoodo', types: ['rock'], heightTiles: 3.5, baseSpeed: 30 },
  186: { name: 'Politoed', types: ['water'], heightTiles: 3.5, baseSpeed: 70 },
  187: { name: 'Hoppip', types: ['grass', 'flying'], heightTiles: 2.6, baseSpeed: 50 },
  188: { name: 'Skiploom', types: ['grass', 'flying'], heightTiles: 2, baseSpeed: 80 },
  189: { name: 'Jumpluff', types: ['grass', 'flying'], heightTiles: 2.1, baseSpeed: 110 },
  190: { name: 'Aipom', types: ['normal'], heightTiles: 2.1, baseSpeed: 85 },
  191: { name: 'Sunkern', types: ['grass'], heightTiles: 1.8, baseSpeed: 30 },
  192: { name: 'Sunflora', types: ['grass'], heightTiles: 2.9, baseSpeed: 30 },
  193: { name: 'Yanma', types: ['bug', 'flying'], heightTiles: 3, baseSpeed: 95 },
  194: { name: 'Wooper', types: ['water', 'ground'], heightTiles: 1.75, baseSpeed: 15 },
  195: { name: 'Quagsire', types: ['water', 'ground'], heightTiles: 3.7, baseSpeed: 35 },
  196: { name: 'Espeon', types: ['psychic'], heightTiles: 3.1, baseSpeed: 110 },
  197: { name: 'Umbreon', types: ['dark'], heightTiles: 3.3, baseSpeed: 65 },
  198: { name: 'Murkrow', types: ['dark', 'flying'], heightTiles: 2.2, baseSpeed: 91 },
  199: { name: 'Slowking', types: ['water', 'psychic'], heightTiles: 3.7, baseSpeed: 30 },
  200: { name: 'Misdreavus', types: ['ghost'], heightTiles: 2.6, baseSpeed: 85 },
  201: { name: 'Unown', types: ['psychic'], heightTiles: 2.2, baseSpeed: 48 },
  202: { name: 'Wobbuffet', types: ['psychic'], heightTiles: 2.4, baseSpeed: 33 },
  203: { name: 'Girafarig', types: ['normal', 'psychic'], heightTiles: 4.4, baseSpeed: 85 },
  204: { name: 'Pineco', types: ['bug'], heightTiles: 2.5, baseSpeed: 15 },
  205: { name: 'Forretress', types: ['bug', 'steel'], heightTiles: 3.3, baseSpeed: 40 },
  206: { name: 'Dunsparce', types: ['normal'], heightTiles: 1.4, baseSpeed: 45 },
  207: { name: 'Gligar', types: ['ground', 'flying'], heightTiles: 3.5, baseSpeed: 85 },
  208: { name: 'Steelix', types: ['steel', 'ground'], heightTiles: 10, baseSpeed: 30 },
  209: { name: 'Snubbull', types: ['fairy'], heightTiles: 2.4, baseSpeed: 30 },
  210: { name: 'Granbull', types: ['fairy'], heightTiles: 3.2, baseSpeed: 45 },
  211: { name: 'Qwilfish', types: ['water', 'poison'], heightTiles: 2.35, baseSpeed: 85 },
  212: { name: 'Scizor', types: ['bug', 'steel'], heightTiles: 5.1, baseSpeed: 65 },
  213: { name: 'Shuckle', types: ['bug', 'rock'], heightTiles: 2.15, baseSpeed: 5 },
  214: { name: 'Heracross', types: ['bug', 'fighting'], heightTiles: 4.4, baseSpeed: 85 },
  215: { name: 'Sneasel', types: ['dark', 'ice'], heightTiles: 3.25, baseSpeed: 115 },
  216: { name: 'Teddiursa', types: ['normal'], heightTiles: 2.1, baseSpeed: 40 },
  217: { name: 'Ursaring', types: ['normal'], heightTiles: 5.1, baseSpeed: 55 },
  218: { name: 'Slugma', types: ['fire'], heightTiles: 2.8, baseSpeed: 20 },
  219: { name: 'Magcargo', types: ['fire', 'rock'], heightTiles: 3.2, baseSpeed: 30 },
  220: { name: 'Swinub', types: ['ice', 'ground'], heightTiles: 1.2, baseSpeed: 50 },
  221: { name: 'Piloswine', types: ['ice', 'ground'], heightTiles: 3.1, baseSpeed: 50 },
  222: { name: 'Corsola', types: ['water', 'rock'], heightTiles: 1.9, baseSpeed: 35 },
  223: { name: 'Remoraid', types: ['water'], heightTiles: 2.4, baseSpeed: 65 },
  224: { name: 'Octillery', types: ['water'], heightTiles: 2.7, baseSpeed: 45 },
  225: { name: 'Delibird', types: ['ice', 'flying'], heightTiles: 3.1, baseSpeed: 75 },
  226: { name: 'Mantine', types: ['water', 'flying'], heightTiles: 5.7, baseSpeed: 70 },
  227: { name: 'Skarmory', types: ['steel', 'flying'], heightTiles: 4.8, baseSpeed: 70 },
  228: { name: 'Houndour', types: ['dark', 'fire'], heightTiles: 2.55, baseSpeed: 65 },
  229: { name: 'Houndoom', types: ['dark', 'fire'], heightTiles: 4.2, baseSpeed: 95 },
  230: { name: 'Kingdra', types: ['water', 'dragon'], heightTiles: 4.1, baseSpeed: 85 },
  231: { name: 'Phanpy', types: ['ground'], heightTiles: 2.2, baseSpeed: 40 },
  232: { name: 'Donphan', types: ['ground'], heightTiles: 3.5, baseSpeed: 50 },
  233: { name: 'Porygon2', types: ['normal'], heightTiles: 2.4, baseSpeed: 60 },
  234: { name: 'Stantler', types: ['normal'], heightTiles: 4.2, baseSpeed: 85 },
  235: { name: 'Smeargle', types: ['normal'], heightTiles: 2.5, baseSpeed: 75 },
  236: { name: 'Tyrogue', types: ['fighting'], heightTiles: 2.6, baseSpeed: 35 },
  237: { name: 'Hitmontop', types: ['fighting'], heightTiles: 2.6, baseSpeed: 70 },
  238: { name: 'Smoochum', types: ['ice', 'psychic'], heightTiles: 2, baseSpeed: 65 },
  239: { name: 'Elekid', types: ['electric'], heightTiles: 2.4, baseSpeed: 95 },
  240: { name: 'Magby', types: ['fire'], heightTiles: 2.6, baseSpeed: 83 },
  241: { name: 'Miltank', types: ['normal'], heightTiles: 3.7, baseSpeed: 100 },
  242: { name: 'Blissey', types: ['normal'], heightTiles: 3.4, baseSpeed: 55 },
  243: { name: 'Raikou', types: ['electric'], heightTiles: 3.3, baseSpeed: 115 },
  244: { name: 'Entei', types: ['fire'], heightTiles: 3.5, baseSpeed: 100 },
  245: { name: 'Suicune', types: ['water'], heightTiles: 3.3, baseSpeed: 85 },
  246: { name: 'Larvitar', types: ['rock', 'ground'], heightTiles: 2.6, baseSpeed: 41 },
  247: { name: 'Pupitar', types: ['rock', 'ground'], heightTiles: 3.6, baseSpeed: 51 },
  248: { name: 'Tyranitar', types: ['rock', 'dark'], heightTiles: 4, baseSpeed: 61 },
  249: { name: 'Lugia', types: ['psychic', 'flying'], heightTiles: 7, baseSpeed: 110 },
  250: { name: 'Ho-Oh', types: ['fire', 'flying'], heightTiles: 7, baseSpeed: 90 },
  251: { name: 'Celebi', types: ['psychic', 'grass'], heightTiles: 2.6, baseSpeed: 100 },
  252: { name: 'Treecko', types: ['grass'], heightTiles: 2.2, baseSpeed: 70 },
  253: { name: 'Grovyle', types: ['grass'], heightTiles: 3.1, baseSpeed: 95 },
  254: { name: 'Sceptile', types: ['grass'], heightTiles: 4.8, baseSpeed: 120 },
  255: { name: 'Torchic', types: ['fire'], heightTiles: 2, baseSpeed: 45 },
  256: { name: 'Combusken', types: ['fire', 'fighting'], heightTiles: 3.1, baseSpeed: 55 },
  257: { name: 'Blaziken', types: ['fire', 'fighting'], heightTiles: 5.3, baseSpeed: 80 },
  258: { name: 'Mudkip', types: ['water'], heightTiles: 2, baseSpeed: 40 },
  259: { name: 'Marshtomp', types: ['water', 'ground'], heightTiles: 2.6, baseSpeed: 50 },
  260: { name: 'Swampert', types: ['water', 'ground'], heightTiles: 4.4, baseSpeed: 60 },
  261: { name: 'Poochyena', types: ['dark'], heightTiles: 2.2, baseSpeed: 35 },
  262: { name: 'Mightyena', types: ['dark'], heightTiles: 3.3, baseSpeed: 70 },
  263: { name: 'Zigzagoon', types: ['normal'], heightTiles: 2, baseSpeed: 60 },
  264: { name: 'Linoone', types: ['normal'], heightTiles: 2.2, baseSpeed: 100 },
  265: { name: 'Wurmple', types: ['bug'], heightTiles: 1.8, baseSpeed: 20 },
  266: { name: 'Silcoon', types: ['bug'], heightTiles: 2.4, baseSpeed: 15 },
  267: { name: 'Beautifly', types: ['bug', 'flying'], heightTiles: 3.3, baseSpeed: 65 },
  268: { name: 'Cascoon', types: ['bug'], heightTiles: 2.6, baseSpeed: 15 },
  269: { name: 'Dustox', types: ['bug', 'poison'], heightTiles: 3.7, baseSpeed: 65 },
  270: { name: 'Lotad', types: ['water', 'grass'], heightTiles: 2.2, baseSpeed: 30 },
  271: { name: 'Lombre', types: ['water', 'grass'], heightTiles: 3.7, baseSpeed: 50 },
  272: { name: 'Ludicolo', types: ['water', 'grass'], heightTiles: 4.4, baseSpeed: 70 },
  273: { name: 'Seedot', types: ['grass'], heightTiles: 2.2, baseSpeed: 30 },
  274: { name: 'Nuzleaf', types: ['grass', 'dark'], heightTiles: 3.3, baseSpeed: 60 },
  275: { name: 'Shiftry', types: ['grass', 'dark'], heightTiles: 4, baseSpeed: 80 },
  276: { name: 'Taillow', types: ['normal', 'flying'], heightTiles: 1.8, baseSpeed: 85 },
  277: { name: 'Swellow', types: ['normal', 'flying'], heightTiles: 2.6, baseSpeed: 125 },
  278: { name: 'Wingull', types: ['water', 'flying'], heightTiles: 2.4, baseSpeed: 85 },
  279: { name: 'Pelipper', types: ['water', 'flying'], heightTiles: 3.7, baseSpeed: 65 },
  280: { name: 'Ralts', types: ['psychic', 'fairy'], heightTiles: 2, baseSpeed: 40 },
  281: { name: 'Kirlia', types: ['psychic', 'fairy'], heightTiles: 2.9, baseSpeed: 50 },
  282: { name: 'Gardevoir', types: ['psychic', 'fairy'], heightTiles: 4.6, baseSpeed: 80 },
  283: { name: 'Surskit', types: ['bug', 'water'], heightTiles: 2.2, baseSpeed: 65 },
  284: { name: 'Masquerain', types: ['bug', 'flying'], heightTiles: 2.9, baseSpeed: 80 },
  285: { name: 'Shroomish', types: ['grass'], heightTiles: 2, baseSpeed: 35 },
  286: { name: 'Breloom', types: ['grass', 'fighting'], heightTiles: 3.7, baseSpeed: 70 },
  287: { name: 'Slakoth', types: ['normal'], heightTiles: 2.9, baseSpeed: 30 },
  288: { name: 'Vigoroth', types: ['normal'], heightTiles: 4.2, baseSpeed: 90 },
  289: { name: 'Slaking', types: ['normal'], heightTiles: 5.5, baseSpeed: 100 },
  290: { name: 'Nincada', types: ['bug', 'ground'], heightTiles: 2.2, baseSpeed: 40 },
  291: { name: 'Ninjask', types: ['bug', 'flying'], heightTiles: 2.9, baseSpeed: 160 },
  292: { name: 'Shedinja', types: ['bug', 'ghost'], heightTiles: 2.9, baseSpeed: 40 },
  293: { name: 'Whismur', types: ['normal'], heightTiles: 2.4, baseSpeed: 28 },
  294: { name: 'Loudred', types: ['normal'], heightTiles: 3.3, baseSpeed: 48 },
  295: { name: 'Exploud', types: ['normal'], heightTiles: 4.4, baseSpeed: 68 },
  296: { name: 'Makuhita', types: ['fighting'], heightTiles: 3.3, baseSpeed: 25 },
  297: { name: 'Hariyama', types: ['fighting'], heightTiles: 6.2, baseSpeed: 50 },
  298: { name: 'Azurill', types: ['normal', 'fairy'], heightTiles: 1.5, baseSpeed: 20 },
  299: { name: 'Nosepass', types: ['rock'], heightTiles: 3.3, baseSpeed: 30 },
  300: { name: 'Skitty', types: ['normal'], heightTiles: 2.4, baseSpeed: 50 },
  301: { name: 'Delcatty', types: ['normal'], heightTiles: 3.5, baseSpeed: 90 },
  302: { name: 'Sableye', types: ['dark', 'ghost'], heightTiles: 2.2, baseSpeed: 50 },
  303: { name: 'Mawile', types: ['steel', 'fairy'], heightTiles: 2.4, baseSpeed: 50 },
  304: { name: 'Aron', types: ['steel', 'rock'], heightTiles: 2, baseSpeed: 30 },
  305: { name: 'Lairon', types: ['steel', 'rock'], heightTiles: 3.1, baseSpeed: 40 },
  306: { name: 'Aggron', types: ['steel', 'rock'], heightTiles: 5.7, baseSpeed: 50 },
  307: { name: 'Meditite', types: ['fighting', 'psychic'], heightTiles: 2.4, baseSpeed: 60 },
  308: { name: 'Medicham', types: ['fighting', 'psychic'], heightTiles: 4, baseSpeed: 80 },
  309: { name: 'Electrike', types: ['electric'], heightTiles: 2.4, baseSpeed: 65 },
  310: { name: 'Manectric', types: ['electric'], heightTiles: 4.4, baseSpeed: 105 },
  311: { name: 'Plusle', types: ['electric'], heightTiles: 2, baseSpeed: 95 },
  312: { name: 'Minun', types: ['electric'], heightTiles: 2, baseSpeed: 95 },
  313: { name: 'Volbeat', types: ['bug'], heightTiles: 2.6, baseSpeed: 85 },
  314: { name: 'Illumise', types: ['bug'], heightTiles: 2.4, baseSpeed: 85 },
  315: { name: 'Roselia', types: ['grass', 'poison'], heightTiles: 1.8, baseSpeed: 65 },
  316: { name: 'Gulpin', types: ['poison'], heightTiles: 2, baseSpeed: 40 },
  317: { name: 'Swalot', types: ['poison'], heightTiles: 4.8, baseSpeed: 55 },
  318: { name: 'Carvanha', types: ['water', 'dark'], heightTiles: 2.9, baseSpeed: 65 },
  319: { name: 'Sharpedo', types: ['water', 'dark'], heightTiles: 5.1, baseSpeed: 95 },
  320: { name: 'Wailmer', types: ['water'], heightTiles: 5.5, baseSpeed: 60 },
  321: { name: 'Wailord', types: ['water'], heightTiles: 9, baseSpeed: 60 },
  322: { name: 'Numel', types: ['fire', 'ground'], heightTiles: 2.6, baseSpeed: 35 },
  323: { name: 'Camerupt', types: ['fire', 'ground'], heightTiles: 5.3, baseSpeed: 40 },
  324: { name: 'Torkoal', types: ['fire'], heightTiles: 2.2, baseSpeed: 20 },
  325: { name: 'Spoink', types: ['psychic'], heightTiles: 2.6, baseSpeed: 60 },
  326: { name: 'Grumpig', types: ['psychic'], heightTiles: 3.1, baseSpeed: 80 },
  327: { name: 'Spinda', types: ['normal'], heightTiles: 3.5, baseSpeed: 60 },
  328: { name: 'Trapinch', types: ['ground'], heightTiles: 2.6, baseSpeed: 10 },
  329: { name: 'Vibrava', types: ['ground', 'dragon'], heightTiles: 3.5, baseSpeed: 70 },
  330: { name: 'Flygon', types: ['ground', 'dragon'], heightTiles: 5.5, baseSpeed: 100 },
  331: { name: 'Cacnea', types: ['grass'], heightTiles: 2, baseSpeed: 35 },
  332: { name: 'Cacturne', types: ['grass', 'dark'], heightTiles: 4, baseSpeed: 55 },
  333: { name: 'Swablu', types: ['normal', 'flying'], heightTiles: 2, baseSpeed: 50 },
  334: { name: 'Altaria', types: ['dragon', 'flying'], heightTiles: 3.5, baseSpeed: 80 },
  335: { name: 'Zangoose', types: ['normal'], heightTiles: 4, baseSpeed: 90 },
  336: { name: 'Seviper', types: ['poison'], heightTiles: 7, baseSpeed: 65 },
  337: { name: 'Lunatone', types: ['rock', 'psychic'], heightTiles: 3.3, baseSpeed: 70 },
  338: { name: 'Solrock', types: ['rock', 'psychic'], heightTiles: 3.7, baseSpeed: 70 },
  339: { name: 'Barboach', types: ['water', 'ground'], heightTiles: 2, baseSpeed: 60 },
  340: { name: 'Whiscash', types: ['water', 'ground'], heightTiles: 3.1, baseSpeed: 60 },
  341: { name: 'Corphish', types: ['water'], heightTiles: 2.4, baseSpeed: 35 },
  342: { name: 'Crawdaunt', types: ['water', 'dark'], heightTiles: 3.5, baseSpeed: 55 },
  343: { name: 'Baltoy', types: ['ground', 'psychic'], heightTiles: 2.2, baseSpeed: 55 },
  344: { name: 'Claydol', types: ['ground', 'psychic'], heightTiles: 4.4, baseSpeed: 75 },
  345: { name: 'Lileep', types: ['rock', 'grass'], heightTiles: 3.3, baseSpeed: 23 },
  346: { name: 'Cradily', types: ['rock', 'grass'], heightTiles: 4.4, baseSpeed: 43 },
  347: { name: 'Anorith', types: ['rock', 'bug'], heightTiles: 2.6, baseSpeed: 75 },
  348: { name: 'Armaldo', types: ['rock', 'bug'], heightTiles: 4.4, baseSpeed: 45 },
  349: { name: 'Feebas', types: ['water'], heightTiles: 2.4, baseSpeed: 80 },
  350: { name: 'Milotic', types: ['water'], heightTiles: 9, baseSpeed: 81 },
  351: { name: 'Castform', types: ['normal'], heightTiles: 1.8, baseSpeed: 70 },
  352: { name: 'Kecleon', types: ['normal'], heightTiles: 3.3, baseSpeed: 40 },
  353: { name: 'Shuppet', types: ['ghost'], heightTiles: 2.4, baseSpeed: 45 },
  354: { name: 'Banette', types: ['ghost'], heightTiles: 3.5, baseSpeed: 65 },
  355: { name: 'Duskull', types: ['ghost'], heightTiles: 2.9, baseSpeed: 25 },
  356: { name: 'Dusclops', types: ['ghost'], heightTiles: 4.6, baseSpeed: 25 },
  357: { name: 'Tropius', types: ['grass', 'flying'], heightTiles: 5.5, baseSpeed: 51 },
  358: { name: 'Chimecho', types: ['psychic'], heightTiles: 2.4, baseSpeed: 65 },
  359: { name: 'Absol', types: ['dark'], heightTiles: 3.7, baseSpeed: 75 },
  360: { name: 'Wynaut', types: ['psychic'], heightTiles: 2.4, baseSpeed: 23 },
  361: { name: 'Snorunt', types: ['ice'], heightTiles: 2.6, baseSpeed: 50 },
  362: { name: 'Glalie', types: ['ice'], heightTiles: 4.4, baseSpeed: 80 },
  363: { name: 'Spheal', types: ['ice', 'water'], heightTiles: 1.75, baseSpeed: 25 },
  364: { name: 'Sealeo', types: ['ice', 'water'], heightTiles: 3.5, baseSpeed: 45 },
  365: { name: 'Walrein', types: ['ice', 'water'], heightTiles: 4.2, baseSpeed: 65 },
  366: { name: 'Clamperl', types: ['water'], heightTiles: 2, baseSpeed: 32 },
  367: { name: 'Huntail', types: ['water'], heightTiles: 4.8, baseSpeed: 52 },
  368: { name: 'Gorebyss', types: ['water'], heightTiles: 5.1, baseSpeed: 52 },
  369: { name: 'Relicanth', types: ['water', 'rock'], heightTiles: 3.3, baseSpeed: 55 },
  370: { name: 'Luvdisc', types: ['water'], heightTiles: 2.4, baseSpeed: 97 },
  371: { name: 'Bagon', types: ['dragon'], heightTiles: 2.4, baseSpeed: 50 },
  372: { name: 'Shelgon', types: ['dragon'], heightTiles: 3.5, baseSpeed: 50 },
  373: { name: 'Salamence', types: ['dragon', 'flying'], heightTiles: 4.4, baseSpeed: 100 },
  374: { name: 'Beldum', types: ['steel', 'psychic'], heightTiles: 2.4, baseSpeed: 30 },
  375: { name: 'Metang', types: ['steel', 'psychic'], heightTiles: 3.7, baseSpeed: 50 },
  376: { name: 'Metagross', types: ['steel', 'psychic'], heightTiles: 4.6, baseSpeed: 70 },
  377: { name: 'Regirock', types: ['rock'], heightTiles: 4.8, baseSpeed: 50 },
  378: { name: 'Regice', types: ['ice'], heightTiles: 5.1, baseSpeed: 50 },
  379: { name: 'Registeel', types: ['steel'], heightTiles: 5.3, baseSpeed: 50 },
  380: { name: 'Latias', types: ['dragon', 'psychic'], heightTiles: 4.2, baseSpeed: 110 },
  381: { name: 'Latios', types: ['dragon', 'psychic'], heightTiles: 5.5, baseSpeed: 110 },
  382: { name: 'Kyogre', types: ['water'], heightTiles: 9, baseSpeed: 90 },
  383: { name: 'Groudon', types: ['ground'], heightTiles: 8.8, baseSpeed: 90 },
  384: { name: 'Rayquaza', types: ['dragon', 'flying'], heightTiles: 9, baseSpeed: 95 },
  385: { name: 'Jirachi', types: ['steel', 'psychic'], heightTiles: 1.8, baseSpeed: 100 },
  386: { name: 'Deoxys', types: ['psychic'], heightTiles: 4.8, baseSpeed: 150 },
  387: { name: 'Turtwig', types: ['grass'], heightTiles: 2, baseSpeed: 31 },
  388: { name: 'Grotle', types: ['grass'], heightTiles: 3.5, baseSpeed: 36 },
  389: { name: 'Torterra', types: ['grass', 'ground'], heightTiles: 5.9, baseSpeed: 56 },
  390: { name: 'Chimchar', types: ['fire'], heightTiles: 2.2, baseSpeed: 61 },
  391: { name: 'Monferno', types: ['fire', 'fighting'], heightTiles: 3.1, baseSpeed: 81 },
  392: { name: 'Infernape', types: ['fire', 'fighting'], heightTiles: 3.7, baseSpeed: 108 },
  393: { name: 'Piplup', types: ['water'], heightTiles: 2, baseSpeed: 40 },
  394: { name: 'Prinplup', types: ['water'], heightTiles: 2.9, baseSpeed: 50 },
  395: { name: 'Empoleon', types: ['water', 'steel'], heightTiles: 4.8, baseSpeed: 60 },
  396: { name: 'Starly', types: ['normal', 'flying'], heightTiles: 1.8, baseSpeed: 60 },
  397: { name: 'Staravia', types: ['normal', 'flying'], heightTiles: 2.4, baseSpeed: 80 },
  398: { name: 'Staraptor', types: ['normal', 'flying'], heightTiles: 3.7, baseSpeed: 100 },
  399: { name: 'Bidoof', types: ['normal'], heightTiles: 2.2, baseSpeed: 31 },
  400: { name: 'Bibarel', types: ['normal', 'water'], heightTiles: 3.3, baseSpeed: 71 },
  401: { name: 'Kricketot', types: ['bug'], heightTiles: 1.8, baseSpeed: 25 },
  402: { name: 'Kricketune', types: ['bug'], heightTiles: 3.3, baseSpeed: 65 },
  403: { name: 'Shinx', types: ['electric'], heightTiles: 2.2, baseSpeed: 45 },
  404: { name: 'Luxio', types: ['electric'], heightTiles: 3.1, baseSpeed: 60 },
  405: { name: 'Luxray', types: ['electric'], heightTiles: 4.2, baseSpeed: 70 },
  406: { name: 'Budew', types: ['grass', 'poison'], heightTiles: 1.5, baseSpeed: 55 },
  407: { name: 'Roserade', types: ['grass', 'poison'], heightTiles: 3.1, baseSpeed: 90 },
  408: { name: 'Cranidos', types: ['rock'], heightTiles: 3.1, baseSpeed: 58 },
  409: { name: 'Rampardos', types: ['rock'], heightTiles: 4.6, baseSpeed: 58 },
  410: { name: 'Shieldon', types: ['rock', 'steel'], heightTiles: 2.2, baseSpeed: 30 },
  411: { name: 'Bastiodon', types: ['rock', 'steel'], heightTiles: 4, baseSpeed: 30 },
  412: { name: 'Burmy', types: ['bug'], heightTiles: 1.5, baseSpeed: 36 },
  413: { name: 'Wormadam', types: ['bug', 'grass'], heightTiles: 2.2, baseSpeed: 36 },
  414: { name: 'Mothim', types: ['bug', 'flying'], heightTiles: 3.1, baseSpeed: 66 },
  415: { name: 'Combee', types: ['bug', 'flying'], heightTiles: 1.8, baseSpeed: 70 },
  416: { name: 'Vespiquen', types: ['bug', 'flying'], heightTiles: 3.7, baseSpeed: 40 },
  417: { name: 'Pachirisu', types: ['electric'], heightTiles: 2, baseSpeed: 95 },
  418: { name: 'Buizel', types: ['water'], heightTiles: 2.6, baseSpeed: 85 },
  419: { name: 'Floatzel', types: ['water'], heightTiles: 3.5, baseSpeed: 115 },
  420: { name: 'Cherubi', types: ['grass'], heightTiles: 2, baseSpeed: 35 },
  421: { name: 'Cherrim', types: ['grass'], heightTiles: 2.2, baseSpeed: 85 },
  422: { name: 'Shellos', types: ['water'], heightTiles: 1.8, baseSpeed: 34 },
  423: { name: 'Gastrodon', types: ['water', 'ground'], heightTiles: 3.1, baseSpeed: 39 },
  424: { name: 'Ambipom', types: ['normal'], heightTiles: 3.7, baseSpeed: 115 },
  425: { name: 'Drifloon', types: ['ghost', 'flying'], heightTiles: 2, baseSpeed: 70 },
  426: { name: 'Drifblim', types: ['ghost', 'flying'], heightTiles: 3.7, baseSpeed: 80 },
  427: { name: 'Buneary', types: ['normal'], heightTiles: 2, baseSpeed: 85 },
  428: { name: 'Lopunny', types: ['normal'], heightTiles: 3.7, baseSpeed: 105 },
  429: { name: 'Mismagius', types: ['ghost'], heightTiles: 3.1, baseSpeed: 105 },
  430: { name: 'Honchkrow', types: ['dark', 'flying'], heightTiles: 3.1, baseSpeed: 71 },
  431: { name: 'Glameow', types: ['normal'], heightTiles: 2.2, baseSpeed: 85 },
  432: { name: 'Purugly', types: ['normal'], heightTiles: 3.3, baseSpeed: 112 },
  433: { name: 'Chingling', types: ['psychic'], heightTiles: 1.5, baseSpeed: 45 },
  434: { name: 'Stunky', types: ['poison', 'dark'], heightTiles: 2, baseSpeed: 74 },
  435: { name: 'Skuntank', types: ['poison', 'dark'], heightTiles: 3.3, baseSpeed: 84 },
  436: { name: 'Bronzor', types: ['steel', 'psychic'], heightTiles: 2.2, baseSpeed: 23 },
  437: { name: 'Bronzong', types: ['steel', 'psychic'], heightTiles: 4, baseSpeed: 33 },
  438: { name: 'Bonsly', types: ['rock'], heightTiles: 2.2, baseSpeed: 10 },
  439: { name: 'Mime Jr.', types: ['psychic', 'fairy'], heightTiles: 2.4, baseSpeed: 60 },
  440: { name: 'Happiny', types: ['normal'], heightTiles: 2.4, baseSpeed: 30 },
  441: { name: 'Chatot', types: ['normal', 'flying'], heightTiles: 2.2, baseSpeed: 91 },
  442: { name: 'Spiritomb', types: ['ghost', 'dark'], heightTiles: 3.3, baseSpeed: 35 },
  443: { name: 'Gible', types: ['dragon', 'ground'], heightTiles: 1.9, baseSpeed: 42 },
  444: { name: 'Gabite', types: ['dragon', 'ground'], heightTiles: 3.75, baseSpeed: 82 },
  445: { name: 'Garchomp', types: ['dragon', 'ground'], heightTiles: 4.35, baseSpeed: 102 },
  446: { name: 'Munchlax', types: ['normal'], heightTiles: 2.4, baseSpeed: 5 },
  447: { name: 'Riolu', types: ['fighting'], heightTiles: 2.6, baseSpeed: 60 },
  448: { name: 'Lucario', types: ['fighting', 'steel'], heightTiles: 3.7, baseSpeed: 90 },
  449: { name: 'Hippopotas', types: ['ground'], heightTiles: 1.6, baseSpeed: 32 },
  450: { name: 'Hippowdon', types: ['ground'], heightTiles: 4.4, baseSpeed: 47 },
  451: { name: 'Skorupi', types: ['poison', 'bug'], heightTiles: 2.9, baseSpeed: 65 },
  452: { name: 'Drapion', types: ['poison', 'dark'], heightTiles: 4, baseSpeed: 95 },
  453: { name: 'Croagunk', types: ['poison', 'fighting'], heightTiles: 2.6, baseSpeed: 50 },
  454: { name: 'Toxicroak', types: ['poison', 'fighting'], heightTiles: 4, baseSpeed: 85 },
  455: { name: 'Carnivine', types: ['grass'], heightTiles: 4.2, baseSpeed: 46 },
  456: { name: 'Finneon', types: ['water'], heightTiles: 2, baseSpeed: 66 },
  457: { name: 'Lumineon', types: ['water'], heightTiles: 3.7, baseSpeed: 91 },
  458: { name: 'Mantyke', types: ['water', 'flying'], heightTiles: 3.3, baseSpeed: 50 },
  459: { name: 'Snover', types: ['grass', 'ice'], heightTiles: 3.3, baseSpeed: 40 },
  460: { name: 'Abomasnow', types: ['grass', 'ice'], heightTiles: 5.9, baseSpeed: 60 },
  461: { name: 'Weavile', types: ['dark', 'ice'], heightTiles: 3.5, baseSpeed: 125 },
  462: { name: 'Magnezone', types: ['electric', 'steel'], heightTiles: 3.7, baseSpeed: 60 },
  463: { name: 'Lickilicky', types: ['normal'], heightTiles: 4.8, baseSpeed: 50 },
  464: { name: 'Rhyperior', types: ['ground', 'rock'], heightTiles: 6.4, baseSpeed: 40 },
  465: { name: 'Tangrowth', types: ['grass'], heightTiles: 3.5, baseSpeed: 50 },
  466: { name: 'Electivire', types: ['electric'], heightTiles: 5.1, baseSpeed: 95 },
  467: { name: 'Magmortar', types: ['fire'], heightTiles: 4.6, baseSpeed: 83 },
  468: { name: 'Togekiss', types: ['fairy', 'flying'], heightTiles: 4.4, baseSpeed: 80 },
  469: { name: 'Yanmega', types: ['bug', 'flying'], heightTiles: 5.3, baseSpeed: 95 },
  470: { name: 'Leafeon', types: ['grass'], heightTiles: 3.3, baseSpeed: 95 },
  471: { name: 'Glaceon', types: ['ice'], heightTiles: 2.9, baseSpeed: 65 },
  472: { name: 'Gliscor', types: ['ground', 'flying'], heightTiles: 5.5, baseSpeed: 95 },
  473: { name: 'Mamoswine', types: ['ice', 'ground'], heightTiles: 6.6, baseSpeed: 80 },
  474: { name: 'Porygon-Z', types: ['normal'], heightTiles: 3.1, baseSpeed: 90 },
  475: { name: 'Gallade', types: ['psychic', 'fighting'], heightTiles: 4.6, baseSpeed: 80 },
  476: { name: 'Probopass', types: ['rock', 'steel'], heightTiles: 4.2, baseSpeed: 40 },
  477: { name: 'Dusknoir', types: ['ghost'], heightTiles: 5.9, baseSpeed: 45 },
  478: { name: 'Froslass', types: ['ice', 'ghost'], heightTiles: 4, baseSpeed: 110 },
  479: { name: 'Rotom', types: ['electric', 'ghost'], heightTiles: 1.8, baseSpeed: 91 },
  480: { name: 'Uxie', types: ['psychic'], heightTiles: 1.8, baseSpeed: 95 },
  481: { name: 'Mesprit', types: ['psychic'], heightTiles: 1.8, baseSpeed: 80 },
  482: { name: 'Azelf', types: ['psychic'], heightTiles: 1.8, baseSpeed: 115 },
  483: { name: 'Dialga', types: ['steel', 'dragon'], heightTiles: 9, baseSpeed: 90 },
  484: { name: 'Palkia', types: ['water', 'dragon'], heightTiles: 9, baseSpeed: 100 },
  485: { name: 'Heatran', types: ['fire', 'steel'], heightTiles: 4.8, baseSpeed: 77 },
  486: { name: 'Regigigas', types: ['normal'], heightTiles: 9, baseSpeed: 100 },
  487: { name: 'Giratina', types: ['ghost', 'dragon'], heightTiles: 9, baseSpeed: 90 },
  488: { name: 'Cresselia', types: ['psychic'], heightTiles: 4.4, baseSpeed: 85 },
  489: { name: 'Phione', types: ['water'], heightTiles: 2, baseSpeed: 80 },
  490: { name: 'Manaphy', types: ['water'], heightTiles: 1.8, baseSpeed: 100 },
  491: { name: 'Darkrai', types: ['dark'], heightTiles: 4.4, baseSpeed: 125 },
  492: { name: 'Shaymin', types: ['grass'], heightTiles: 1.5, baseSpeed: 100 },
  493: { name: 'Arceus', types: ['normal'], heightTiles: 8.1, baseSpeed: 120 },
};

const _heightEntries = Object.entries(POKEMON_CONFIG).map(([dex, c]) => [
  Number(dex),
  c.heightTiles
]);

/** @type {Record<number, number>} — dex → tile height (same keys as legacy `pokemon-heights.js`) */
export const POKEMON_HEIGHTS = Object.fromEntries(_heightEntries);

/**
 * @param {number} dexId
 * @returns {PokemonSpeciesConfig & { dexId: number, behavior: PokemonBehaviorTuning } | null}
 */
export function getPokemonConfig(dexId) {
  const n = Number(dexId);
  if (!Number.isFinite(n)) return null;
  const dex = Math.floor(n);
  if (dex < 1 || dex > 493) return null;
  const row = POKEMON_CONFIG[dex];
  if (!row) return null;
  const behavior = {
    walkSpeedMul: 1,
    scatterWeight: 1,
    turnBias: 0,
    ...(row.behavior || {})
  };
  return { dexId: dex, ...row, behavior };
}

