/**
 * National Dex #1–251 species data for gameplay tuning (height, motion, type logic).
 * Regenerate: `node scripts/build-pokemon-config.mjs` (needs network).
 *
 * @typedef {'bug'|'dark'|'dragon'|'electric'|'fairy'|'fighting'|'fire'|'flying'|'ghost'|'grass'|'ground'|'ice'|'normal'|'poison'|'psychic'|'rock'|'steel'|'water'} PokemonTypeSlug
 *
 * @typedef {Object} PokemonBehaviorTuning
 * @property {number} [walkSpeedMul] — multiply walk tick scale (1 = default)
 * @property {number} [scatterWeight] — encounter / prop scatter preference weight
 * @property {number} [turnBias] — −1..1 AI turn randomness bias (reserved)
 *
 * @typedef {Object} PokemonSpeciesConfig
 * @property {string} name — matches encounter strings in national-dex-registry.js where possible
 * @property {PokemonTypeSlug[]} types — slot order primary → secondary; Gen 1 chart overrides baked in (see script)
 * @property {number} heightTiles — visual / collider height in tile units
 * @property {number} baseSpeed — main-series base Speed (for motion / turn order tuning)
 * @property {PokemonBehaviorTuning} [behavior] — optional per-species behavior overrides
 */

/** @type {Record<number, PokemonSpeciesConfig>} */
export const POKEMON_CONFIG = {
  1: { name: 'Bulbasaur', types: ['grass', 'poison'], heightTiles: 2.1, baseSpeed: 45 },
  2: { name: 'Ivysaur', types: ['grass', 'poison'], heightTiles: 2.2, baseSpeed: 60 },
  3: { name: 'Venusaur', types: ['grass', 'poison'], heightTiles: 2.5, baseSpeed: 80 },
  4: { name: 'Charmander', types: ['fire'], heightTiles: 2.5, baseSpeed: 65 },
  5: { name: 'Charmeleon', types: ['fire'], heightTiles: 3.5, baseSpeed: 80 },
  6: { name: 'Charizard', types: ['fire', 'flying'], heightTiles: 3.5, baseSpeed: 100 },
  7: { name: 'Squirtle', types: ['water'], heightTiles: 1.5, baseSpeed: 43 },
  8: { name: 'Wartortle', types: ['water'], heightTiles: 2.5, baseSpeed: 58 },
  9: { name: 'Blastoise', types: ['water'], heightTiles: 3.1, baseSpeed: 78 },
  10: { name: 'Caterpie', types: ['bug'], heightTiles: 2, baseSpeed: 45 },
  11: { name: 'Metapod', types: ['bug'], heightTiles: 2.1, baseSpeed: 30 },
  12: { name: 'Butterfree', types: ['bug', 'flying'], heightTiles: 3.3, baseSpeed: 70 },
  13: { name: 'Weedle', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 50 },
  14: { name: 'Kakuna', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 35 },
  15: { name: 'Beedrill', types: ['bug', 'poison'], heightTiles: 3, baseSpeed: 75 },
  16: { name: 'Pidgey', types: ['normal', 'flying'], heightTiles: 2, baseSpeed: 56 },
  17: { name: 'Pidgeotto', types: ['normal', 'flying'], heightTiles: 3.2, baseSpeed: 71 },
  18: { name: 'Pidgeot', types: ['normal', 'flying'], heightTiles: 3.7, baseSpeed: 101 },
  19: { name: 'Rattata', types: ['normal'], heightTiles: 1.6, baseSpeed: 72 },
  20: { name: 'Raticate', types: ['normal'], heightTiles: 3.5, baseSpeed: 97 },
  21: { name: 'Spearow', types: ['normal', 'flying'], heightTiles: 2.5, baseSpeed: 70 },
  22: { name: 'Fearow', types: ['normal', 'flying'], heightTiles: 5.2, baseSpeed: 100 },
  23: { name: 'Ekans', types: ['poison'], heightTiles: 2.5, baseSpeed: 55 },
  24: { name: 'Arbok', types: ['poison'], heightTiles: 3.5, baseSpeed: 80 },
  25: { name: 'Pikachu', types: ['electric'], heightTiles: 2.9, baseSpeed: 90 },
  26: { name: 'Raichu', types: ['electric'], heightTiles: 3.5, baseSpeed: 110 },
  27: { name: 'Sandshrew', types: ['ground'], heightTiles: 2.5, baseSpeed: 40 },
  28: { name: 'Sandslash', types: ['ground'], heightTiles: 3, baseSpeed: 65 },
  29: { name: 'Nidoran♀', types: ['poison'], heightTiles: 2.5, baseSpeed: 41 },
  30: { name: 'Nidorina', types: ['poison'], heightTiles: 3.5, baseSpeed: 56 },
  31: { name: 'Nidoqueen', types: ['poison', 'ground'], heightTiles: 3.5, baseSpeed: 76 },
  32: { name: 'Nidoran♂', types: ['poison'], heightTiles: 2.5, baseSpeed: 50 },
  33: { name: 'Nidorino', types: ['poison'], heightTiles: 2.9, baseSpeed: 65 },
  34: { name: 'Nidoking', types: ['poison', 'ground'], heightTiles: 3.6, baseSpeed: 85 },
  35: { name: 'Clefairy', types: ['normal'], heightTiles: 2.5, baseSpeed: 35 },
  36: { name: 'Clefable', types: ['normal'], heightTiles: 3.5, baseSpeed: 60 },
  37: { name: 'Vulpix', types: ['fire'], heightTiles: 1.7, baseSpeed: 65 },
  38: { name: 'Ninetales', types: ['fire'], heightTiles: 3.1, baseSpeed: 100 },
  39: { name: 'Jigglypuff', types: ['normal'], heightTiles: 2.1, baseSpeed: 20 },
  40: { name: 'Wigglytuff', types: ['normal'], heightTiles: 3.5, baseSpeed: 45 },
  41: { name: 'Zubat', types: ['poison', 'flying'], heightTiles: 2.7, baseSpeed: 55 },
  42: { name: 'Golbat', types: ['poison', 'flying'], heightTiles: 4.1, baseSpeed: 90 },
  43: { name: 'Oddish', types: ['grass', 'poison'], heightTiles: 2, baseSpeed: 30 },
  44: { name: 'Gloom', types: ['grass', 'poison'], heightTiles: 2.1, baseSpeed: 40 },
  45: { name: 'Vileplume', types: ['grass', 'poison'], heightTiles: 3.5, baseSpeed: 50 },
  46: { name: 'Paras', types: ['bug', 'grass'], heightTiles: 1.5, baseSpeed: 25 },
  47: { name: 'Parasect', types: ['bug', 'grass'], heightTiles: 3.5, baseSpeed: 30 },
  48: { name: 'Venonat', types: ['bug', 'poison'], heightTiles: 2.5, baseSpeed: 45 },
  49: { name: 'Venomoth', types: ['bug', 'poison'], heightTiles: 4.1, baseSpeed: 90 },
  50: { name: 'Diglett', types: ['ground'], heightTiles: 1.2, baseSpeed: 95 },
  51: { name: 'Dugtrio', types: ['ground'], heightTiles: 1.8, baseSpeed: 120 },
  52: { name: 'Meowth', types: ['normal'], heightTiles: 2, baseSpeed: 90 },
  53: { name: 'Persian', types: ['normal'], heightTiles: 3.8, baseSpeed: 115 },
  54: { name: 'Psyduck', types: ['water'], heightTiles: 2.5, baseSpeed: 55 },
  55: { name: 'Golduck', types: ['water'], heightTiles: 2.7, baseSpeed: 85 },
  56: { name: 'Mankey', types: ['fighting'], heightTiles: 3.2, baseSpeed: 70 },
  57: { name: 'Primeape', types: ['fighting'], heightTiles: 4.7, baseSpeed: 95 },
  58: { name: 'Growlithe', types: ['fire'], heightTiles: 2.5, baseSpeed: 60 },
  59: { name: 'Arcanine', types: ['fire'], heightTiles: 3.5, baseSpeed: 95 },
  60: { name: 'Poliwag', types: ['water'], heightTiles: 2.5, baseSpeed: 90 },
  61: { name: 'Poliwhirl', types: ['water'], heightTiles: 3.5, baseSpeed: 90 },
  62: { name: 'Poliwrath', types: ['water', 'fighting'], heightTiles: 4.1, baseSpeed: 70 },
  63: { name: 'Abra', types: ['psychic'], heightTiles: 2.5, baseSpeed: 90 },
  64: { name: 'Kadabra', types: ['psychic'], heightTiles: 3.5, baseSpeed: 105 },
  65: { name: 'Alakazam', types: ['psychic'], heightTiles: 4, baseSpeed: 120 },
  66: { name: 'Machop', types: ['fighting'], heightTiles: 2.2, baseSpeed: 35 },
  67: { name: 'Machoke', types: ['fighting'], heightTiles: 3.5, baseSpeed: 45 },
  68: { name: 'Machamp', types: ['fighting'], heightTiles: 3.5, baseSpeed: 55 },
  69: { name: 'Bellsprout', types: ['grass', 'poison'], heightTiles: 2.15, baseSpeed: 40 },
  70: { name: 'Weepinbell', types: ['grass', 'poison'], heightTiles: 3.1, baseSpeed: 55 },
  71: { name: 'Victreebel', types: ['grass', 'poison'], heightTiles: 5.7, baseSpeed: 70 },
  72: { name: 'Tentacool', types: ['water', 'poison'], heightTiles: 2.5, baseSpeed: 70 },
  73: { name: 'Tentacruel', types: ['water', 'poison'], heightTiles: 7.9, baseSpeed: 100 },
  74: { name: 'Geodude', types: ['rock', 'ground'], heightTiles: 1.3, baseSpeed: 20 },
  75: { name: 'Graveler', types: ['rock', 'ground'], heightTiles: 3.1, baseSpeed: 35 },
  76: { name: 'Golem', types: ['rock', 'ground'], heightTiles: 3.2, baseSpeed: 45 },
  77: { name: 'Ponyta', types: ['fire'], heightTiles: 2.6, baseSpeed: 90 },
  78: { name: 'Rapidash', types: ['fire'], heightTiles: 3.9, baseSpeed: 105 },
  79: { name: 'Slowpoke', types: ['water', 'psychic'], heightTiles: 2.5, baseSpeed: 15 },
  80: { name: 'Slowbro', types: ['water', 'psychic'], heightTiles: 3.5, baseSpeed: 30 },
  81: { name: 'Magnemite', types: ['electric'], heightTiles: 2.4, baseSpeed: 45 },
  82: { name: 'Magneton', types: ['electric'], heightTiles: 3.1, baseSpeed: 70 },
  83: { name: 'Farfetch\'d', types: ['normal', 'flying'], heightTiles: 2.1, baseSpeed: 60 },
  84: { name: 'Doduo', types: ['normal', 'flying'], heightTiles: 2.5, baseSpeed: 75 },
  85: { name: 'Dodrio', types: ['normal', 'flying'], heightTiles: 3.6, baseSpeed: 110 },
  86: { name: 'Seel', types: ['water'], heightTiles: 2, baseSpeed: 45 },
  87: { name: 'Dewgong', types: ['water', 'ice'], heightTiles: 3.1, baseSpeed: 70 },
  88: { name: 'Grimer', types: ['poison'], heightTiles: 2.5, baseSpeed: 25 },
  89: { name: 'Muk', types: ['poison'], heightTiles: 3.4, baseSpeed: 50 },
  90: { name: 'Shellder', types: ['water'], heightTiles: 2.2, baseSpeed: 40 },
  91: { name: 'Cloyster', types: ['water', 'ice'], heightTiles: 4.3, baseSpeed: 70 },
  92: { name: 'Gastly', types: ['ghost', 'poison'], heightTiles: 2.5, baseSpeed: 80 },
  93: { name: 'Haunter', types: ['ghost', 'poison'], heightTiles: 3.5, baseSpeed: 95 },
  94: { name: 'Gengar', types: ['ghost', 'poison'], heightTiles: 3.1, baseSpeed: 110 },
  95: { name: 'Onix', types: ['rock', 'ground'], heightTiles: 9, baseSpeed: 70 },
  96: { name: 'Drowzee', types: ['psychic'], heightTiles: 2.7, baseSpeed: 42 },
  97: { name: 'Hypno', types: ['psychic'], heightTiles: 3.8, baseSpeed: 67 },
  98: { name: 'Krabby', types: ['water'], heightTiles: 2.5, baseSpeed: 50 },
  99: { name: 'Kingler', types: ['water'], heightTiles: 4.9, baseSpeed: 75 },
  100: { name: 'Voltorb', types: ['electric'], heightTiles: 2.5, baseSpeed: 100 },
  101: { name: 'Electrode', types: ['electric'], heightTiles: 3.5, baseSpeed: 150 },
  102: { name: 'Exeggcute', types: ['grass', 'psychic'], heightTiles: 2.5, baseSpeed: 40 },
  103: { name: 'Exeggutor', types: ['grass', 'psychic'], heightTiles: 4.2, baseSpeed: 55 },
  104: { name: 'Cubone', types: ['ground'], heightTiles: 2.5, baseSpeed: 35 },
  105: { name: 'Marowak', types: ['ground'], heightTiles: 2.9, baseSpeed: 45 },
  106: { name: 'Hitmonlee', types: ['fighting'], heightTiles: 3.2, baseSpeed: 87 },
  107: { name: 'Hitmonchan', types: ['fighting'], heightTiles: 4.3, baseSpeed: 76 },
  108: { name: 'Lickitung', types: ['normal'], heightTiles: 3.5, baseSpeed: 30 },
  109: { name: 'Koffing', types: ['poison'], heightTiles: 3.2, baseSpeed: 35 },
  110: { name: 'Weezing', types: ['poison'], heightTiles: 4.2, baseSpeed: 60 },
  111: { name: 'Rhyhorn', types: ['ground', 'rock'], heightTiles: 2.5, baseSpeed: 25 },
  112: { name: 'Rhydon', types: ['ground', 'rock'], heightTiles: 3.9, baseSpeed: 40 },
  113: { name: 'Chansey', types: ['normal'], heightTiles: 3.5, baseSpeed: 50 },
  114: { name: 'Tangela', types: ['grass'], heightTiles: 2.6, baseSpeed: 60 },
  115: { name: 'Kangaskhan', types: ['normal'], heightTiles: 4.7, baseSpeed: 90 },
  116: { name: 'Horsea', types: ['water'], heightTiles: 3.2, baseSpeed: 60 },
  117: { name: 'Seadra', types: ['water'], heightTiles: 4.5, baseSpeed: 85 },
  118: { name: 'Goldeen', types: ['water'], heightTiles: 2.5, baseSpeed: 63 },
  119: { name: 'Seaking', types: ['water'], heightTiles: 3.5, baseSpeed: 68 },
  120: { name: 'Staryu', types: ['water'], heightTiles: 1.9, baseSpeed: 85 },
  121: { name: 'Starmie', types: ['water', 'psychic'], heightTiles: 2.5, baseSpeed: 115 },
  122: { name: 'Mr. Mime', types: ['psychic'], heightTiles: 3.5, baseSpeed: 90 },
  123: { name: 'Scyther', types: ['bug', 'flying'], heightTiles: 3.5, baseSpeed: 105 },
  124: { name: 'Jynx', types: ['ice', 'psychic'], heightTiles: 2.3, baseSpeed: 95 },
  125: { name: 'Electabuzz', types: ['electric'], heightTiles: 3.5, baseSpeed: 105 },
  126: { name: 'Magmar', types: ['fire'], heightTiles: 3.5, baseSpeed: 93 },
  127: { name: 'Pinsir', types: ['bug'], heightTiles: 3.1, baseSpeed: 85 },
  128: { name: 'Tauros', types: ['normal'], heightTiles: 3.4, baseSpeed: 110 },
  129: { name: 'Magikarp', types: ['water'], heightTiles: 1.5, baseSpeed: 80 },
  130: { name: 'Gyarados', types: ['water', 'flying'], heightTiles: 8, baseSpeed: 81 },
  131: { name: 'Lapras', types: ['water', 'ice'], heightTiles: 3.5, baseSpeed: 60 },
  132: { name: 'Ditto', types: ['normal'], heightTiles: 2, baseSpeed: 48 },
  133: { name: 'Eevee', types: ['normal'], heightTiles: 1.9, baseSpeed: 55 },
  134: { name: 'Vaporeon', types: ['water'], heightTiles: 3, baseSpeed: 65 },
  135: { name: 'Jolteon', types: ['electric'], heightTiles: 3, baseSpeed: 130 },
  136: { name: 'Flareon', types: ['fire'], heightTiles: 2.5, baseSpeed: 65 },
  137: { name: 'Porygon', types: ['normal'], heightTiles: 2.5, baseSpeed: 40 },
  138: { name: 'Omanyte', types: ['rock', 'water'], heightTiles: 2.1, baseSpeed: 35 },
  139: { name: 'Omastar', types: ['rock', 'water'], heightTiles: 3, baseSpeed: 55 },
  140: { name: 'Kabuto', types: ['rock', 'water'], heightTiles: 1.5, baseSpeed: 55 },
  141: { name: 'Kabutops', types: ['rock', 'water'], heightTiles: 3.5, baseSpeed: 80 },
  142: { name: 'Aerodactyl', types: ['rock', 'flying'], heightTiles: 4.5, baseSpeed: 130 },
  143: { name: 'Snorlax', types: ['normal'], heightTiles: 6.2, baseSpeed: 30 },
  144: { name: 'Articuno', types: ['ice', 'flying'], heightTiles: 7, baseSpeed: 85 },
  145: { name: 'Zapdos', types: ['electric', 'flying'], heightTiles: 7, baseSpeed: 100 },
  146: { name: 'Moltres', types: ['fire', 'flying'], heightTiles: 7, baseSpeed: 90 },
  147: { name: 'Dratini', types: ['dragon'], heightTiles: 2, baseSpeed: 50 },
  148: { name: 'Dragonair', types: ['dragon'], heightTiles: 3, baseSpeed: 70 },
  149: { name: 'Dragonite', types: ['dragon', 'flying'], heightTiles: 4.4, baseSpeed: 80 },
  150: { name: 'Mewtwo', types: ['psychic'], heightTiles: 4.1, baseSpeed: 130 },
  151: { name: 'Mew', types: ['psychic'], heightTiles: 3.5, baseSpeed: 100 },
  152: { name: 'Chikorita', types: ['grass'], heightTiles: 3.1, baseSpeed: 45 },
  153: { name: 'Bayleef', types: ['grass'], heightTiles: 3.7, baseSpeed: 60 },
  154: { name: 'Meganium', types: ['grass'], heightTiles: 5.1, baseSpeed: 80 },
  155: { name: 'Cyndaquil', types: ['fire'], heightTiles: 2.2, baseSpeed: 65 },
  156: { name: 'Quilava', types: ['fire'], heightTiles: 3.1, baseSpeed: 80 },
  157: { name: 'Typhlosion', types: ['fire'], heightTiles: 4.8, baseSpeed: 100 },
  158: { name: 'Totodile', types: ['water'], heightTiles: 2.4, baseSpeed: 43 },
  159: { name: 'Croconaw', types: ['water'], heightTiles: 3.5, baseSpeed: 58 },
  160: { name: 'Feraligatr', types: ['water'], heightTiles: 6.2, baseSpeed: 78 },
  161: { name: 'Sentret', types: ['normal'], heightTiles: 2.9, baseSpeed: 20 },
  162: { name: 'Furret', types: ['normal'], heightTiles: 5.1, baseSpeed: 90 },
  163: { name: 'Hoothoot', types: ['normal', 'flying'], heightTiles: 1.85, baseSpeed: 50 },
  164: { name: 'Noctowl', types: ['normal', 'flying'], heightTiles: 4.6, baseSpeed: 70 },
  165: { name: 'Ledyba', types: ['bug', 'flying'], heightTiles: 2.3, baseSpeed: 55 },
  166: { name: 'Ledian', types: ['bug', 'flying'], heightTiles: 3.2, baseSpeed: 85 },
  167: { name: 'Spinarak', types: ['bug', 'poison'], heightTiles: 1.2, baseSpeed: 30 },
  168: { name: 'Ariados', types: ['bug', 'poison'], heightTiles: 3.5, baseSpeed: 40 },
  169: { name: 'Crobat', types: ['poison', 'flying'], heightTiles: 4.8, baseSpeed: 130 },
  170: { name: 'Chinchou', types: ['water', 'electric'], heightTiles: 2.2, baseSpeed: 67 },
  171: { name: 'Lanturn', types: ['water', 'electric'], heightTiles: 3.7, baseSpeed: 67 },
  172: { name: 'Pichu', types: ['electric'], heightTiles: 1.8, baseSpeed: 60 },
  173: { name: 'Cleffa', types: ['fairy'], heightTiles: 1.1, baseSpeed: 15 },
  174: { name: 'Igglybuff', types: ['normal', 'fairy'], heightTiles: 1.1, baseSpeed: 15 },
  175: { name: 'Togepi', types: ['fairy'], heightTiles: 1.8, baseSpeed: 20 },
  176: { name: 'Togetic', types: ['fairy', 'flying'], heightTiles: 2.7, baseSpeed: 40 },
  177: { name: 'Natu', types: ['psychic', 'flying'], heightTiles: 1.5, baseSpeed: 70 },
  178: { name: 'Xatu', types: ['psychic', 'flying'], heightTiles: 2.5, baseSpeed: 95 },
  179: { name: 'Mareep', types: ['electric'], heightTiles: 2.4, baseSpeed: 35 },
  180: { name: 'Flaaffy', types: ['electric'], heightTiles: 3.0, baseSpeed: 45 },
  181: { name: 'Ampharos', types: ['electric'], heightTiles: 4.2, baseSpeed: 55 },
  182: { name: 'Bellossom', types: ['grass'], heightTiles: 1.5, baseSpeed: 50 },
  183: { name: 'Marill', types: ['water', 'fairy'], heightTiles: 2, baseSpeed: 40 },
  184: { name: 'Azumarill', types: ['water', 'fairy'], heightTiles: 2.9, baseSpeed: 50 },
  185: { name: 'Sudowoodo', types: ['rock'], heightTiles: 3.5, baseSpeed: 30 },
  186: { name: 'Politoed', types: ['water'], heightTiles: 3.5, baseSpeed: 70 },
  187: { name: 'Hoppip', types: ['grass', 'flying'], heightTiles: 2.6, baseSpeed: 50 },
  188: { name: 'Skiploom', types: ['grass', 'flying'], heightTiles: 2.0, baseSpeed: 80 },
  189: { name: 'Jumpluff', types: ['grass', 'flying'], heightTiles: 2.1, baseSpeed: 110 },
  190: { name: 'Aipom', types: ['normal'], heightTiles: 2.1, baseSpeed: 85 },
  191: { name: 'Sunkern', types: ['grass'], heightTiles: 1.8, baseSpeed: 30 },
  192: { name: 'Sunflora', types: ['grass'], heightTiles: 2.9, baseSpeed: 30 },
  193: { name: 'Yanma', types: ['bug', 'flying'], heightTiles: 3.0, baseSpeed: 95 },
  194: { name: 'Wooper', types: ['water', 'ground'], heightTiles: 1.75, baseSpeed: 15 },
  195: { name: 'Quagsire', types: ['water', 'ground'], heightTiles: 3.7, baseSpeed: 35 },
  196: { name: 'Espeon', types: ['psychic'], heightTiles: 3.1, baseSpeed: 110 },
  197: { name: 'Umbreon', types: ['dark'], heightTiles: 3.3, baseSpeed: 65 },
  198: { name: 'Murkrow', types: ['dark', 'flying'], heightTiles: 2.2, baseSpeed: 91 },
  199: { name: 'Slowking', types: ['water', 'psychic'], heightTiles: 3.7, baseSpeed: 30 },
  200: { name: 'Misdreavus', types: ['ghost'], heightTiles: 2.6, baseSpeed: 85 },
  201: { name: 'Unown', types: ['psychic'], heightTiles: 2.2, baseSpeed: 48 },
  202: { name: 'Wobbuffet', types: ['psychic'], heightTiles: 2.4, baseSpeed: 33 },
  203: { name: 'Girafarig', types: ['normal', 'psychic'], heightTiles: 4.4, baseSpeed: 85 },
  204: { name: 'Pineco', types: ['bug'], heightTiles: 2.5, baseSpeed: 15 },
  205: { name: 'Forretress', types: ['bug', 'steel'], heightTiles: 3.3, baseSpeed: 40 },
  206: { name: 'Dunsparce', types: ['normal'], heightTiles: 1.4, baseSpeed: 45 },
  207: { name: 'Gligar', types: ['ground', 'flying'], heightTiles: 3.5, baseSpeed: 85 },
  208: { name: 'Steelix', types: ['steel', 'ground'], heightTiles: 10, baseSpeed: 30 },
  209: { name: 'Snubbull', types: ['fairy'], heightTiles: 2.4, baseSpeed: 30 },
  210: { name: 'Granbull', types: ['fairy'], heightTiles: 4.2, baseSpeed: 45 },
  211: { name: 'Qwilfish', types: ['water', 'poison'], heightTiles: 2.2, baseSpeed: 85 },
  212: { name: 'Scizor', types: ['bug', 'steel'], heightTiles: 5.1, baseSpeed: 65 },
  213: { name: 'Shuckle', types: ['bug', 'rock'], heightTiles: 2.4, baseSpeed: 5 },
  214: { name: 'Heracross', types: ['bug', 'fighting'], heightTiles: 4.4, baseSpeed: 85 },
  215: { name: 'Sneasel', types: ['dark', 'ice'], heightTiles: 3.1, baseSpeed: 115 },
  216: { name: 'Teddiursa', types: ['normal'], heightTiles: 2.4, baseSpeed: 40 },
  217: { name: 'Ursaring', types: ['normal'], heightTiles: 5.1, baseSpeed: 55 },
  218: { name: 'Slugma', types: ['fire'], heightTiles: 2.6, baseSpeed: 20 },
  219: { name: 'Magcargo', types: ['fire', 'rock'], heightTiles: 2.9, baseSpeed: 30 },
  220: { name: 'Swinub', types: ['ice', 'ground'], heightTiles: 2, baseSpeed: 50 },
  221: { name: 'Piloswine', types: ['ice', 'ground'], heightTiles: 3.5, baseSpeed: 50 },
  222: { name: 'Corsola', types: ['water', 'rock'], heightTiles: 2.4, baseSpeed: 35 },
  223: { name: 'Remoraid', types: ['water'], heightTiles: 2.4, baseSpeed: 65 },
  224: { name: 'Octillery', types: ['water'], heightTiles: 3.1, baseSpeed: 45 },
  225: { name: 'Delibird', types: ['ice', 'flying'], heightTiles: 3.1, baseSpeed: 75 },
  226: { name: 'Mantine', types: ['water', 'flying'], heightTiles: 5.7, baseSpeed: 70 },
  227: { name: 'Skarmory', types: ['steel', 'flying'], heightTiles: 4.8, baseSpeed: 70 },
  228: { name: 'Houndour', types: ['dark', 'fire'], heightTiles: 2.4, baseSpeed: 65 },
  229: { name: 'Houndoom', types: ['dark', 'fire'], heightTiles: 4.2, baseSpeed: 95 },
  230: { name: 'Kingdra', types: ['water', 'dragon'], heightTiles: 5.1, baseSpeed: 85 },
  231: { name: 'Phanpy', types: ['ground'], heightTiles: 2.2, baseSpeed: 40 },
  232: { name: 'Donphan', types: ['ground'], heightTiles: 3.5, baseSpeed: 50 },
  233: { name: 'Porygon2', types: ['normal'], heightTiles: 2.4, baseSpeed: 60 },
  234: { name: 'Stantler', types: ['normal'], heightTiles: 4.2, baseSpeed: 85 },
  235: { name: 'Smeargle', types: ['normal'], heightTiles: 3.7, baseSpeed: 75 },
  236: { name: 'Tyrogue', types: ['fighting'], heightTiles: 2.6, baseSpeed: 35 },
  237: { name: 'Hitmontop', types: ['fighting'], heightTiles: 4.2, baseSpeed: 70 },
  238: { name: 'Smoochum', types: ['ice', 'psychic'], heightTiles: 2, baseSpeed: 65 },
  239: { name: 'Elekid', types: ['electric'], heightTiles: 2.4, baseSpeed: 95 },
  240: { name: 'Magby', types: ['fire'], heightTiles: 2.6, baseSpeed: 83 },
  241: { name: 'Miltank', types: ['normal'], heightTiles: 3.7, baseSpeed: 100 },
  242: { name: 'Blissey', types: ['normal'], heightTiles: 4.4, baseSpeed: 55 },
  243: { name: 'Raikou', types: ['electric'], heightTiles: 3.3, baseSpeed: 115 },
  244: { name: 'Entei', types: ['fire'], heightTiles: 3.5, baseSpeed: 100 },
  245: { name: 'Suicune', types: ['water'], heightTiles: 3.3, baseSpeed: 85 },
  246: { name: 'Larvitar', types: ['rock', 'ground'], heightTiles: 2.6, baseSpeed: 41 },
  247: { name: 'Pupitar', types: ['rock', 'ground'], heightTiles: 3.6, baseSpeed: 51 },
  248: { name: 'Tyranitar', types: ['rock', 'dark'], heightTiles: 4.0, baseSpeed: 61 },
  249: { name: 'Lugia', types: ['psychic', 'flying'], heightTiles: 7, baseSpeed: 110 },
  250: { name: 'Ho-Oh', types: ['fire', 'flying'], heightTiles: 7, baseSpeed: 90 },
  251: { name: 'Celebi', types: ['psychic', 'grass'], heightTiles: 2.6, baseSpeed: 100 },
};

const _heightEntries = Object.entries(POKEMON_CONFIG).map(([dex, c]) => [
  Number(dex),
  c.heightTiles
]);

/** @type {Record<number, number>} — dex → tile height (same keys as legacy `pokemon-heights.js`) */
export const POKEMON_HEIGHTS = Object.fromEntries(_heightEntries);

/**
 * @param {number} dexId
 * @returns {PokemonSpeciesConfig & { dexId: number, behavior: PokemonBehaviorTuning } | null}
 */
export function getPokemonConfig(dexId) {
  const n = Number(dexId);
  if (!Number.isFinite(n)) return null;
  const dex = Math.floor(n);
  if (dex < 1 || dex > 251) return null;
  const row = POKEMON_CONFIG[dex];
  if (!row) return null;
  const behavior = {
    walkSpeedMul: 1,
    scatterWeight: 1,
    turnBias: 0,
    ...(row.behavior || {})
  };
  return { dexId: dex, ...row, behavior };
}

